In [1]:
import torch
import numpy as np

In [9]:
# remember we can create random ints, arrays etc. in numpy

In [4]:
random_array = np.random.randn(3,5)

In [5]:
random_array

array([[ 1.8634492 ,  1.46895565, -0.91979051,  1.75471401,  0.49676865],
       [ 0.19509376,  1.00359541,  1.50266805,  0.16993078, -0.82644217],
       [-1.0509879 ,  0.73897723,  0.78123137,  0.97101043,  0.29397012]])

In [6]:
type(random_array)

numpy.ndarray

In [7]:
random_array.shape

(3, 5)

In [8]:
random_array.ndim

2

In [11]:
# let's do this in pytorch

In [14]:
random_matrix = torch.rand(size=(3, 5))

In [15]:
random_matrix

tensor([[0.3006, 0.0785, 0.3279, 0.3726, 0.2978],
        [0.5812, 0.9269, 0.0805, 0.7052, 0.5975],
        [0.4344, 0.8963, 0.4542, 0.3550, 0.6655]])

In [16]:
random_matrix.ndim

2

In [17]:
random_matrix.shape

torch.Size([3, 5])

In [18]:
random_matrix.dtype

torch.float32

In [19]:
# we generally use 32 * 32 or 224 * 224 images in vision dl problems

In [20]:
random_image_matrix = torch.rand(size=(224, 224, 3))

In [21]:
random_image_matrix

tensor([[[0.9495, 0.6002, 0.0137],
         [0.2648, 0.9643, 0.4416],
         [0.4042, 0.2345, 0.4622],
         ...,
         [0.5193, 0.0519, 0.3034],
         [0.7972, 0.0676, 0.0443],
         [0.2874, 0.1335, 0.8244]],

        [[0.4572, 0.6239, 0.0181],
         [0.5185, 0.9106, 0.0629],
         [0.9248, 0.0880, 0.9291],
         ...,
         [0.8003, 0.2234, 0.2084],
         [0.4928, 0.8391, 0.9397],
         [0.9683, 0.0958, 0.2484]],

        [[0.8879, 0.2406, 0.5587],
         [0.4789, 0.5843, 0.6681],
         [0.4572, 0.4118, 0.1333],
         ...,
         [0.9000, 0.8646, 0.9161],
         [0.0464, 0.7846, 0.0123],
         [0.4117, 0.8043, 0.8590]],

        ...,

        [[0.1956, 0.7160, 0.6199],
         [0.3465, 0.2552, 0.9546],
         [0.8243, 0.2867, 0.3721],
         ...,
         [0.6121, 0.8875, 0.5550],
         [0.1011, 0.3950, 0.7962],
         [0.1719, 0.0967, 0.1575]],

        [[0.3575, 0.5773, 0.6300],
         [0.2395, 0.6060, 0.3420],
         [0.

In [22]:
random_image_matrix.ndim

3

In [23]:
random_image_matrix.shape

torch.Size([224, 224, 3])

In [24]:
# we can create zeros and ones if we need some for matrix multiplication or anything else

In [26]:
zeros = torch.zeros(size=(3, 2))

In [27]:
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [28]:
ones = torch.ones(size=(3, 4))

In [29]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
# or we can create ranges

In [31]:
vector_with_arange = torch.arange(start=0, end=10, step=1)

In [32]:
vector_with_arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
vector_with_arange = torch.arange(start=0, end=10, step=2)

In [34]:
vector_with_arange

tensor([0, 2, 4, 6, 8])

In [35]:
# let's say i need a similar vector with ones

In [36]:
similar_ones = torch.ones_like(input=vector_with_arange)

In [37]:
similar_ones

tensor([1, 1, 1, 1, 1])

In [38]:
# basic math operations

In [39]:
tensor = torch.tensor([1, 2, 3])

In [40]:
tensor + 15

tensor([16, 17, 18])

In [41]:
tensor * 12

tensor([12, 24, 36])

In [42]:
tensor * 3.14

tensor([3.1400, 6.2800, 9.4200])

In [43]:
tensor

tensor([1, 2, 3])

In [44]:
tensor = tensor + 10

In [45]:
tensor

tensor([11, 12, 13])

In [46]:
# we also have native methods for that

In [47]:
tensor.subtract(10)

tensor([1, 2, 3])

In [48]:
tensor

tensor([11, 12, 13])

In [49]:
tensor = tensor.subtract(10)

In [50]:
tensor

tensor([1, 2, 3])

In [51]:
tensor.multiply(20)

tensor([20, 40, 60])

In [52]:
tensor.add(20)

tensor([21, 22, 23])

In [53]:
tensor.divide(2)

tensor([0.5000, 1.0000, 1.5000])

In [54]:
# can we only operate with scalars?

In [55]:
tensor * tensor

tensor([1, 4, 9])

In [56]:
tensor + tensor

tensor([2, 4, 6])

In [57]:
tensor - tensor

tensor([0, 0, 0])

In [58]:
tensor / tensor

tensor([1., 1., 1.])

In [59]:
# beware, in this case shapes should make sense

In [60]:
tensor2 = torch.tensor([4,5])

In [62]:
tensor + tensor2

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [63]:
tensor * tensor2

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0